USE [master]
GO
/****** Object:  Database [BloggingCMS]    Script Date: 23-03-2025 22:30:02 ******/
CREATE DATABASE [BloggingCMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BloggingCMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BloggingCMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BloggingCMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BloggingCMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BloggingCMS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BloggingCMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BloggingCMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BloggingCMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BloggingCMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BloggingCMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BloggingCMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [BloggingCMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BloggingCMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BloggingCMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BloggingCMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BloggingCMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BloggingCMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BloggingCMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BloggingCMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BloggingCMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BloggingCMS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BloggingCMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BloggingCMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BloggingCMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BloggingCMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BloggingCMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BloggingCMS] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [BloggingCMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BloggingCMS] SET RECOVERY FULL 
GO
ALTER DATABASE [BloggingCMS] SET  MULTI_USER 
GO
ALTER DATABASE [BloggingCMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BloggingCMS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BloggingCMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BloggingCMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BloggingCMS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BloggingCMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BloggingCMS', N'ON'
GO
ALTER DATABASE [BloggingCMS] SET QUERY_STORE = ON
GO
ALTER DATABASE [BloggingCMS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BloggingCMS]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 23-03-2025 22:30:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BlogMedias]    Script Date: 23-03-2025 22:30:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlogMedias](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BlogPostId] [int] NOT NULL,
	[MediaUrl] [nvarchar](max) NULL,
	[MediaType] [nvarchar](max) NULL,
 CONSTRAINT [PK_BlogMedias] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BlogPosts]    Script Date: 23-03-2025 22:30:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlogPosts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NULL,
	[Content] [nvarchar](max) NULL,
	[SeoTitle] [nvarchar](max) NULL,
	[SeoDescription] [nvarchar](max) NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[Published] [bit] NOT NULL,
	[AuthorId] [int] NOT NULL,
	[ClickCount] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_BlogPosts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 23-03-2025 22:30:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](450) NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[Role] [nvarchar](max) NULL,
	[FirstName] [nvarchar](max) NULL,
	[LastName] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_BlogMedias_BlogPostId]    Script Date: 23-03-2025 22:30:02 ******/
CREATE NONCLUSTERED INDEX [IX_BlogMedias_BlogPostId] ON [dbo].[BlogMedias]
(
	[BlogPostId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BlogPosts_AuthorId]    Script Date: 23-03-2025 22:30:02 ******/
CREATE NONCLUSTERED INDEX [IX_BlogPosts_AuthorId] ON [dbo].[BlogPosts]
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BlogPosts_UserId]    Script Date: 23-03-2025 22:30:02 ******/
CREATE NONCLUSTERED INDEX [IX_BlogPosts_UserId] ON [dbo].[BlogPosts]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Users_Email]    Script Date: 23-03-2025 22:30:02 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Users_Email] ON [dbo].[Users]
(
	[Email] ASC
)
WHERE ([Email] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BlogPosts] ADD  DEFAULT ((0)) FOR [ClickCount]
GO
ALTER TABLE [dbo].[BlogMedias]  WITH CHECK ADD  CONSTRAINT [FK_BlogMedias_BlogPosts_BlogPostId] FOREIGN KEY([BlogPostId])
REFERENCES [dbo].[BlogPosts] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BlogMedias] CHECK CONSTRAINT [FK_BlogMedias_BlogPosts_BlogPostId]
GO
ALTER TABLE [dbo].[BlogPosts]  WITH CHECK ADD  CONSTRAINT [FK_BlogPosts_Users_AuthorId] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BlogPosts] CHECK CONSTRAINT [FK_BlogPosts_Users_AuthorId]
GO
ALTER TABLE [dbo].[BlogPosts]  WITH CHECK ADD  CONSTRAINT [FK_BlogPosts_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[BlogPosts] CHECK CONSTRAINT [FK_BlogPosts_Users_UserId]
GO
USE [master]
GO
ALTER DATABASE [BloggingCMS] SET  READ_WRITE 
GO
